---
- hosts: mongod
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  roles:
    - community.mongodb.mongodb_linux
    - community.mongodb.mongodb_repository
    - community.mongodb.mongodb_install
    - community.mongodb.mongodb_mongod

  tasks:
    - name: Initialise MongoDB Replicaset rs0
      community.mongodb.mongodb_replicaset:
        replica_set: "rs0"
        members:
          - "mongodb1"
          - "mongodb2"
          - "mongodb3"
      when: ansible_hostname == "mongodb1"